name: zmanim_alarm
description: Zmanim Alarm - Alarmes basées sur les heures juives
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.4
  geolocator: ^12.0.0
  sqflite: ^2.3.3+1
  path: ^1.9.0
  shared_preferences: ^2.3.2
  provider: ^6.1.2
  permission_handler: ^11.3.1
  intl: ^0.20.2
  alarm: ^4.0.0
  file_selector: ^1.0.0
  path_provider: ^2.1.0
  audioplayers: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/sounds/
